FROM <%= image %>

ENV LANG en_US.UTF-8
ENV CONFIGURE_OPTS --disable-install-rdoc <%= opts %>
ENV JRUBY_OPTS --2.0
ENV DEBIAN_FRONTEND noninteractive

# --no-install-recommends to avoid installing fuse (unsupported in docker < 1.0)
RUN apt-get update && \
    apt-get install --no-install-recommends -y <%= dependencies %> && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir ruby-build && \
    wget -qO- https://github.com/rbenv/ruby-build/archive/<%= ruby_build %>.tar.gz | \
    tar xz -C ruby-build/ --strip-components 1 && \
    cd ruby-build && \
    ./bin/ruby-build <%= ruby %> /usr/local && rm -rf ruby-build

RUN gem install bundler <%= gems %>

WORKDIR /rails_app
